# Generated by Django 5.0.6 on 2024-05-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='lastname',
            new_name='subject',
        ),
    ]
